const alumni = [
  { name: 'Ashpreet Kaur', description: 'SDE III @Google', logo: 'google_logo' },
  { name: 'Disha Kala', description: 'SDE II @Microsoft', logo: 'microsoft_logo' },
  { name: 'Saransh Jain', description: 'SDE II @Amazon', logo: 'amazon_logo' },
  { name: 'Yash Tripathi', description: 'SDE II @Zomato', logo: 'zomato_logo' },
  { name: 'Divyansh Singh', description: 'Director @Global Brain', logo: 'globalbrain_logo' },
  { name: 'Rais Ali', description: 'SDE III @DMG', logo: 'dmg_logo' },
  { name: 'Gauri Shankar', description: 'Scientist B @CDOT', logo: 'cdotindia_logo' },
  { name: 'Bhupesh Soni', description: 'Officer @GOI', logo: 'goi_logo' },
  { name: 'Anita Gadhwal', description: 'SDE III @Flipkart', logo: 'flipkart_logo' },
  { name: 'Nishchay Shakya', description: 'Senior Analyst @Capgemini', logo: 'capgemini_logo' },
  { name: 'Gaurav Agarwal', description: 'Founder & CEO, TejasAI', logo: 'tejasai_logo' },
  { name: 'Kunal Verma', description: 'Founder & CEO, InfraHive', logo: 'infrahive_logo' },
  { name: 'Prashrya Rao', description: 'Asst. Manager, BOA', logo: 'bank_of_america_logo' },
  { name: 'Yashash Jain', description: 'ISRO Scientist @SAC', logo: 'sac_logo.jpg' },
  { name: 'Deependra Nyati', description: 'Assistant Officer, MeitY', logo: 'meity_logo' },
  { name: 'Akarshit Gupta', description: 'SDE III @Expedia', logo: 'expedia_logo' },
  { name: 'Akash Tureha', description: 'SDE III @MyNaksh', logo: 'mynaksh_logo' },
  { name: 'Omkar Deshmukh', description: 'SDE @Google', logo: 'google_logo' },
  { name: 'Ankur Agarwal', description: 'SDE II @Coinbase', logo: 'coinbase_logo' },
  { name: 'Bilal Hassan', description: 'Senior TC @Sprinklr', logo: 'sprinklr_logo' },
  { name: 'Ashwini Kumar', description: 'DC Consultant @Deloitte', logo: 'deloitte_logo' },
  { name: 'Suraj Saini', description: 'SDE III @CashKaro', logo: 'cashkaro_logo' },
  { name: 'Mukesh Mahadev', description: 'SDE III @BitGo', logo: 'bitgo_logo' },
  { name: 'Himanshu Goyal', description: 'SDE III @Nykaa', logo: 'nykaa_logo' },
  { name: 'Ankit Bhardwaj', description: 'SWE II @New Relic', logo: 'new_relic_logo' },
  { name: 'Abhinav Jain', description: 'SDE @Motive', logo: 'motive_logo' },
  { name: 'Sanchit Goyal', description: 'Category Manager @Flipkart', logo: 'flipkart_logo' },
  { name: 'Lokesh Gome', description: 'Senior SDE @Paisabazaar', logo: 'paisabazaar_logo' },
];

export { alumni };
