const plcmtHigh = [
  { name: 'Shiwang Aryan', description: 'SDE @Amazon', logo: 'amazon_logo' },
  { name: 'Bongi Satyendra', description: 'SDE @Skylattice', logo: 'skylattice_logo' },
  { name: 'Tarsh Swarnkar', description: 'SDE @Writesonic (YC S21)', logo: 'writesonic_logo' },
  { name: 'Partik Malasi', description: 'SDE @Zomato', logo: 'zomato_logo' },
  { name: 'Vikrant Kumar', description: 'SDE @Amazon', logo: 'amazon_logo' },
  { name: 'Ayush Kumar', description: 'SSE @NVIDIA', logo: 'nvidia_logo' },
  { name: 'Bhuvnesh Sahu', description: 'SDE @MoveInSync', logo: 'moveinsync_logo' },
  { name: 'Manas Singh', description: 'SDE @Highspot', logo: 'highspot_logo' },
  { name: 'Jeevan Choudhary', description: 'SE @Tekion', logo: 'tekion_logo' },
  { name: 'Anany Srivastava', description: 'SDE @Tekion', logo: 'tekion_logo' },
  { name: 'Abhishek Pant', description: 'SDE @Amazon', logo: 'amazon_logo' },
  { name: 'Dhairya Majmudar', description: 'SDE @HackerRank', logo: 'hackerrank_logo' },
  { name: 'Hiteshwar Kaushik', description: 'BA @Meesho', logo: 'meesho_logo' },
  { name: 'Vansh Nigam', description: 'BA @Meesho', logo: 'meesho_logo' },
  { name: 'Hari Meena', description: 'Backend @Juspay', logo: 'juspay_logo' },
  { name: 'Nikhil Kumar', description: 'TC @Onelab', logo: 'onelab_logo' },
  { name: 'Aditya Gangwar', description: 'SDE @Typeface', logo: 'typeface_logo' },
  { name: 'Bhavesh Pareek', description: 'AI R&D @OpenText', logo: 'opentext_logo' },
  { name: 'Raunak Agarwal', description: 'SDE @LumberFi', logo: 'lumberfi_logo' },
  { name: 'Harmeet Singh', description: 'SDE @Headout', logo: 'headout_logo' },
  { name: 'Mohit Meerchandani', description: 'BA @Meesho', logo: 'meesho_logo' },
  { name: 'Aaryan Kumar', description: 'SDE @Cashfree Payments', logo: 'cashfree_logo' },
  { name: 'Kanishq Tahalyani', description: 'SWE @Cisco', logo: 'cisco_logo' },
  { name: 'Aman Khare', description: 'Product Analyst @Shipsy', logo: 'shipsy_logo' },
  { name: 'Priyanshu Mishra', description: 'SDE @Truestate', logo: 'truestate_logo' },
  { name: 'Kunal Sharma', description: 'SDE @Samsung', logo: 'samsung_logo' },
  { name: 'Uday Kumar', description: 'SDE @CoinSwitch', logo: 'coinswitch_logo' },
  { name: 'Rohan Saini', description: 'SDE @DataFlow', logo: 'dataflow_logo' },
  { name: 'Utkarsh Pradhan', description: 'SDE @FinacPlus', logo: 'finacplus_logo' },
  { name: 'Devesh Agarwal', description: 'SDE @Goldman Sachs', logo: 'goldman_sachs_logo' },
  { name: 'Ankit Singh', description: 'SDE @Groww', logo: 'groww_logo' },
  { name: 'Kratin Aggarwal', description: 'SDE @OpenText', logo: 'opentext_logo' },
  { name: 'Varad Kulkarni', description: 'SDE @NVIDIA', logo: 'nvidia_logo' },
  { name: 'Devansh Gupta', description: 'SDE @Samsung', logo: 'samsung_logo' },
  { name: 'Himanshu Sharma', description: 'SDE @Groww', logo: 'groww_logo' },
];

export { plcmtHigh };
